### ISSUE TITLE
Share ideas for the JavaScript API

### ISSUE THREAD

**Issue by evancz** [evancz/time-zone-proposal#1]
We need a low-level JavaScript API that gives access to the timezone database.

It should allow the creation of high-level APIs in various languages. So (1) the JavaScript community should be able to make a variety of packages experimenting with APIs and (2) languages like Elm should be able to use it to provide `Date` conversion as part of their ecosystem in a nice way.

In this thread, please learn about [the IANA time zone database](https://www.iana.org/time-zones) and offer suggestions of how that information could be exposed!

**Comment by evancz** [comment]
To accurately get any piece of information, I believe you only need the POSIX time and the name of a time zone from the database. So the API could look like this:

```javascript
var tz = getTimeZone()
// "America/New_York"

var date = toTimeZone(1499363330495, tz)
// { year: 2017, month: 7, day: 6, dayOfWeek: 4, hour: 13, ... }

var year = date.year
// 2017
```

The `toTimeZone` function would return an object with the following fields:

```javascript
{ year, month, day, dayOfWeek, hour, minute, second, millisecond }
```

This way we would not need to rely on any of the existing `Date` API that can crash in surprising ways.

Is this missing anything?

**Comment by evancz** [comment]
Here is a tougher scenario. Say you want Friday at 3pm in PST forever. Figuring out the POSIX times from that will be tricky based on DST and such.

I have a feeling that it may make sense to just give raw access to the time zone database so that corner cases cannot be missed. In the worst case, you can always just parse the data directly. I will think about that more.

**Comment by jweir** [comment]
`toTimeZone` should also return the time zone and the UTC offset. Might want to include nanosecond too.

And maybe call it `inTimeZone` - it is returning the time from one zone to the time in another.

**Comment by jweir** [comment]
And maybe call it inTimeZone - it is returning the time from one zone to the time in another.

**Comment by Fenntasy** [comment]
It would be useful to get a list of all timezones currently available. I don't know if it is possible for a country to decide to split its territory in several timezones or to regroup them, but considering China has only one, I assume it's possible. By having the browsers having a list of them all, it would be possible to construct a selector for users.
It could go further by having more information than name and offset and giving us geolocation for them. I may be going off track here but the best way I know of letting a user chose a timezone is by giving them a map and letting them click on their country (or city). Right now, these are constructed manually with data that may be quite innacurate but I suppose it could be possible to have this data.

And I suppose that the `getTimeZone`  could also take one of these as a parameter to get a specific one?
Like 

```javascript
var tz = getTimeZone("Europe/Paris") 
```

> This way we would not need to rely on any of the existing `Date` API that can crash in surprising ways.

Wouldn't you be relying on it for the timestamp though? You technically could get it from your server or from somewhere else but most of the time, you would want to exchange [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) data to really avoid any chance of having something going wrong. The timestamp could have been converted from your local timezone to a UTC one or the other way around without you knowing.

**Comment by justinmimbs** [comment]
_PST_ refers to a UTC offset (-0800), and converting between UTC time and a local time _using an offset_ is straightforward. Looking up an offset for a time zone, like _America/Los_Angeles_, at a given date and time requires a tz database.

Let's say that:

- `time value` = an unambiguous representation of a moment in time, like POSIX time
- `offset` = difference between UTC and local time
- `time zone` = a location observing the same local time, which may change offsets according to a set of rules (e.g. DST switches)
- `time parts` = ( year, month, day, hour, minute, seconds ); note that _without an offset_, even valid time parts may be ambiguous, e.g. ( 2017, Nov, 5, 1, 30, 0.0 ) refers to two different time values in America/Los_Angeles, as 1:30 AM will be observed twice in that time zone during the switch from DST

You can make pure functions in the following ways:

    (time value, time zone, tz database) => offset
    (time value, offset) => local time parts

    (local time parts, time zone, tz database) => offset
    (local time parts, offset) => time value

JS implementations already provide the current system's offset for any Date object (likely using the IANA time zone database, as the [ECMAScript spec recommends it](http://www.ecma-international.org/ecma-262/6.0/#sec-local-time-zone-adjustment)). What's missing is 1) a way to get the offset for an arbitrary time zone (perhaps [getTimezoneOffset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset) could be modified to take an optional parameter):

```js
    var date = new Date(1499363330495);

    date.getTimezoneOffset('America/Los_Angeles');
    // 420

    date.getTimezoneOffset('America/New_York');
    // 240
```

and 2) a clear way to get the current system's time zone:

```js
    Date.localTimezone();
    // 'America/New_York'
```

**Comment by jweir** [comment]
Going back to your example you have `toTimeZone` which takes a valid time and adjusts for the timezones. Given a valid time and timezone it will always produce a new time. 

```javascript
var time = 1483358400000 //  2017-01-02T12:00:00+0000 UTC
var tz = getTimeZone('US-East');
var time2 = timeInTimeZone(time, tz);  //{ year: 2017, month: 1, day: 2, hour: 7, minute: 0, second: 0, offset: (-5,0), timezone: 'US-East' }, but still 1483358400000 posix 
```

The other function is one which takes a local time and needs to assign a timezone to it.  
```
var local = { year: 2017, month: 3, day: 12, hour: 1, minute: 0, second: 0 };
var tz = getTimeZone('US-East');
var time = localTimeInTimeZone(local, tz); // { year: 2017, month: 3, day: 12, hour: 1, minute: 0, second: 0, offset: (-5,0), timezone: 'US-East' }
```

As @justinmimbs points out such a function can return:
* a time
* an ambiguous time error (for 25 hour days)
* a time not found error for 23 hour days

**Comment by jweir** [comment]
Going back to the `toTimeZone` which takes a POSIX time and adjusts for the timezones. You will need a function to convert back into a POSIX value.

```javascript
var time = 1483358400000 //  2017-01-02T12:00:00+0000 UTC
var tz = getTimeZone('US-East', tzDB);
var time2 = toTimeZone(time, tz);  //{ year: 2017, month: 1, day: 2, hour: 7, minute: 0, second: 0, offset: { hour: -5, minute: 0}, timezone: 'US-East' }, but still 1483358400000 posix 

var tz2 = getTimeZone('US-West', tzDB);
var posixTime2 = toPosix(time2);
var time3 = toTimeZone(posixTime2, tz);  //{ year: 2017, month: 1, day: 2, hour: 4, minute: 0, second: 0, offset: { hour: -8, minute: 0}, timezone: 'US-West' }, but still 1483358400000 posix 
```

Another required function is one which takes a local time and assigns a timezone to it.  
```javascript
var local = { year: 2017, month: 3, day: 12, hour: 1, minute: 0, second: 0 };
//  ^^^^^ no offset or time zone assigned
var tz = getTimeZone('US-East', tzDB);
var time = toLocalTimeZone(local, tz); // { year: 2017, month: 3, day: 12, hour: 1, minute: 0, second: 0, offset: { hour: -5, minute: 0}, timezone: 'US-East' }
```

As @justinmimbs points out local time can be ambiguous (or even impossible). So, such a function can return:
* a time
* an ambiguous time error (for 25 hour days)
* a time not found error for 23 hour days

All of the above would require four types:
The TZ database
POSIX Time
`LocalTime`  (year, month, day, hour, minute, second, millisecond)
`TimeWithZone` (year, month, day, hour, minute, second, millisecond, offset, timezone)

And four functions:
`getTimeZone`
`toTimeZone`
`toPosix`
`toLocalTimeZone`

**Comment by evancz** [comment]
I made some progress by doing design work in Elm to see what we actually needed to make a good API. I have rewritten the readme based on that.
