### ISSUE TITLE
Consider integrating into various TC39 proposals

### ISSUE THREAD

**Issue by littledan** [evancz/time-zone-proposal#2]
This looks like a useful API. Maybe we can get it shipping to developers by integrating it into various TC39 proposals currently under discussion:

- `getLocalTimeZoneName` might be pursued as part of the [`Intl.DisplayNames`](https://github.com/brawer/proposal-intl-displaynames/) proposal
- `getTimeZoneEras` could be proposed as part of TC39's [temporal proposal]()https://github.com/tc39/proposal-temporal), as is under discussion in https://github.com/tc39/proposal-temporal/issues/103 .

**Comment by evancz** [comment]
If you think it could be merged in, please pursue it. I cannot oversee that process personally.

**Comment by littledan** [comment]
Well, if you're interested, you don't have to attend TC39 meetings to get involved. I am wondering, how are you pursuing this proposal as a web standard?

**Comment by evancz** [comment]
I do not know about how TC39 works.

The API here seems like a simple way to let any language or library expose a time API according to their exact needs. To me, that makes sense for a platform that wants to support a broad range of usages. The necessary date algorithms you need from there are documented nicely [here](http://howardhinnant.github.io/date_algorithms.html), so different communities can just implement what makes sense for them!

But when I reached out to people to "take the next step" they did not see the point and I felt pretty discouraged. Given the responses I got, it seems like an investment that is both very costly in terms of time and very risky in terms of chances of panning out, making it difficult to balance with demands and conversations within my own community. So I talked with other Elm contributors (like @rtfeldman) who may be able to put in that investment.

Do you have more detailed information about how to proceed in our case? It would be really great to have something like this API!

**Comment by rtfeldman** [comment]
I'm happy to collaborate on this!

@littledan let me know what I can do to help. 😃

**Comment by littledan** [comment]
I'm sorry you had a discouraging experience! I agree that this is a really important problem to solve. We could pursue this in a number of different standards venues, but I just know TC39 best since I am involved there. Let's see what happens in the discussion in https://github.com/tc39/proposal-temporal/issues/103 and go from there. If we end up not being able to standardize this functionality TC39, I think it would make sense to pursue this as a W3C/WHATWG standard along the lines of the API you have written up.
